---
- name: Import kvm tasks for main distribution
  import_tasks: '{{ ansible_facts.distribution }}.yml'

- name: Import host-based tasks
  import_tasks: '{{ ansible_facts.hostname }}.yml'

- name: Ensure libvirtd is enabled
  systemd:
    name: libvirtd
    state: started
    enabled: yes

- name: Add kincerb to libvirt groups
  user:
    name: kincerb
    append: yes
    groups:
      - libvirt
      - kvm
...
