---
- name: Install libvirt packages
  apt:
    name: '{{ package }}'
  vars:
    package:
      - qemu-kvm
      - libvirt-daemon-system

- name: Configure netplan for bond and bridge
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: 00-installer-config.yaml, dest: /etc/netplan/00-installer-config.yaml }
    - { src: 01-interfaces.yaml, dest: /etc/netplan/01-interfaces.yaml }
    - { src: 02-bonds.yaml, dest: /etc/netplan/02-bonds.yaml }
    - { src: 03-bridges.yaml, dest: /etc/netplan/03-bridges.yaml }
    - { src: 11-bridge-remove-netfilter.conf, dest: /etc/sysctl.d/11-bridge-remove-netfilter.conf }
    - { src: 99-bridge.rules, dest: /etc/udev/rules.d/99-bridge.rules }
  notify:
    - apply netplan

- name: Add bridge to libvirt networks
  copy:
    src: physical-bridge.xml
    dest: /etc/libvirt/qemu/networks/physical-bridge.xml
    owner: root
    group: root
    mode: 0600
  notify:
    restart libvirtd
...
