---
- name: Install libvirt packages
  apt:
    name: '{{ package }}'
  vars:
    package:
      - qemu-kvm
      - libvirt-daemon-system

- name: Configure netplan for bond and bridge
  copy:
    src: "{{ item }}"
    dest: /etc/netplan/{{ item }}
    owner: root
    group: root
    mode: 0644
  loop:
    - 00-installer-config.yaml
    - 01-interfaces.yaml
    - 02-bonds.yaml
    - 03-bridges.yaml
  notify:
    - apply netplan

- name: Add bridge to libvirt networks
  copy:
    src: physical-bridge.xml
    dest: /etc/libvirt/qemu/networks/physical-bridge.xml
    owner: root
    group: root
    mode: 0600
  notify:
    restart libvirtd
...
