---
- hosts: digitalocean

  tasks:
    - name: Update OS
      apt:
        name: '*'
        state: latest
        update_cache: yes
      notify:
        - reboot server

    - name: Install needed packages
      apt:
        name: '{{ package }}'
      vars:
        package:
          - apt-transport-https
          - ca-certificates
          - curl
          - python3-pip
          - python3-venv
          - software-properties-common

    - name: Add apt key from docker
      apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker apt repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install docker-ce
      apt:
        name: docker-ce

    - name: Get docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.25.4/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 755
        checksum: sha256:542e93b1d5106d2769b325f60ba9a0ba087bb96e30dc2c1cb026f0cb642e9aed

    - name: Ensure docker is enabled
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create kincerb
      user:
        name: kincerb
        append: yes
        comment: Brent Kincer
        shell: /bin/bash
        groups:
          - docker

    - name: Add SSH keys for kincerb
      authorized_key:
        user: kincerb
        state: present
        key: '{{ item }}'
      with_file:
        - /Users/kincerb/Google/devbkincer/configs/ssh/kincerb_gpg_auth1.pub
        - /Users/kincerb/Google/devbkincer/configs/ssh/kincerb_gpg_auth2.pub

    - name: Remove SSH keys for root
      authorized_key:
        user: root
        state: absent
        key: '{{ item }}'
      with_file:
        - /Users/kincerb/Google/devbkincer/configs/ssh/kincerb_gpg_auth1.pub
        - /Users/kincerb/Google/devbkincer/configs/ssh/kincerb_gpg_auth2.pub

    - name: Setup sudo for kincerb
      lineinfile:
        path: /etc/sudoers.d/90-cloud-init-users
        state: present
        line: 'kincerb ALL=(ALL) NOPASSWD:ALL'

    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^PermitRootLogin\s+(no|yes)'
        line: 'PermitRootLogin no'
      notify:
        - reload sshd

    - name: Enable agent forwarding
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^[#]?AllowAgentForwarding\s+(no|yes)'
        line: 'AllowAgentForwarding yes'
      notify:
        - reload sshd

    - name: Change SSH port to 8022
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^[#]?Port\s+22'
        line: 'Port 8022'
      notify:
        - reload sshd

    - name: Enable TCP forwading
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^[#]?AllowTcpForwarding\s+(no|yes)'
        line: 'AllowTcpForwarding yes'
      notify:
        - reload sshd

    - name: Enable X11 forwading
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^[#]?X11Forwarding\s+(no|yes)'
        line: 'X11Forwarding yes'
      notify:
        - reload sshd

  handlers:
    - name: reload sshd
      systemd:
        name: sshd
        state: reloaded

    - name: reboot server
      reboot:

...
