---
- name: Gather and display facts
  hosts: all

  tasks:
    - name: Gather standard facts
      ansible.builtin.gather_facts:

    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Print all facts
      ansible.builtin.debug:
        var: ansible_facts
