---
- hosts: all
  become: true
  roles:
    - common

- import_playbook: docker.yml
- import_playbook: kvm.yml
- import_playbook: development.yml
- import_playbook: desktop.yml
- import_playbook: samba.yml
...
