---
- name: Set variables commonly used on all hosts
  hosts: all
  vars:
    home_directory: "{{ ansible_facts['env']['HOME'] }}"
    local_directory: "{{ home_directory }}/.local"
    home_bin_directory: "{{ local_directory }}/bin"
    venvs_directory: "{{ local_directory }}/venvs"
    share_directory: "{{ local_directory }}/share"
    projects_directory: "{{ home_directory }}/Projects"
    config_directory: "{{ home_directory }}/.config"
    ssh_directory: "{{ home_directory }}/.ssh"
    ssh_socket_directory: "{{ ssh_directory }}/socket"
  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

- name: Import common playbook
  import_playbook: common.yml

- name: Import docker playbook
  import_playbook: docker.yml

- name: Import kvm playbook
  import_playbook: kvm.yml

- name: Import kvm-guest playbook
  import_playbook: kvm-guest.yml

- name: Import development playbook
  import_playbook: development.yml

- name: Import desktop playbook
  when: ansible_facts.services["display-manager.service"]["state"] == "active"
  import_playbook: desktop.yml

- name: Import samba playbook
  import_playbook: samba.yml

- name: Import samba-client playbook
  import_playbook: samba-client.yml

- name: Import wireguard playbook
  import_playbook: wireguard.yml
