---
- hosts: all
  gather_facts: false
  tasks:
    - name: Push out personal SSH keys
      authorized_key:
        user: kincerb
        state: present
        key: '{{ item }}'
      with_file:
        - "{{ lookup('env', 'HOME') + '/.ssh/kincerb_gpg_auth1.pub' }}"
        - "{{ lookup('env', 'HOME') + '/.ssh/kincerb_gpg_auth2.pub' }}"
  tags:
    - kincerb
    - never

- hosts: all
  remote_user: mwauto
  gather_facts: false
  tasks:
    - name: Push out mwauto SSH key
      authorized_key:
        user: mwauto
        state: present
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/mwauto_rsa.pub') }}"
        exclusive: True
  tags:
    - mwauto
    - never
...
