---
- name: Install common desktop packages
  become: true
  community.general.pacman:
    name:
      - google-chrome-dev
      - kitty
      - kitty-shell-integration
      - kitty-terminfo
    state: present
    update_cache: yes

- name: Configure kitty
  become: false
  ansible.builtin.template:
    src: templates/kitty.conf.j2
    dest: "{{ home_directory }}/.config/kitty/kitty.conf"
    mode: "0640"
    force: yes
    backup: yes
...
