---
- name: Get nerd fonts and install
  become: false
  vars:
    home_directory: "{{ lookup('env', 'HOME') }}"
    install_directory: "{{ home_directory }}/.local/share/fonts"
  block:
    - name: Create fonts download directory
      ansible.builtin.file:
        path: '{{ home_directory }}/Downloads/fonts'
        state: directory
        mode: '0750'

    - name: Create install directory for fonts
      ansible.builtin.file:
        path: '{{ install_directory }}/{{ item }}'
        state: directory
        mode: '0750'
      loop: '{{ desktop_fonts }}'

    - name: Download fonts
      ansible.builtin.get_url:
        url: 'https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ item }}.zip'
        dest: '{{ home_directory }}/Downloads/fonts'
        mode: '0640'
      loop: '{{ desktop_fonts }}'

    - name: Extract fonts
      ansible.builtin.unarchive:
        src: '{{ home_directory }}/Downloads/fonts/{{ item }}.zip'
        dest: '{{ install_directory }}/{{ item }}'
        remote_src: true
        mode: '0755'
      loop: '{{ desktop_fonts }}'
      notify:
        - Update font cache

  always:
    - name: Remove downloaded fonts
      ansible.builtin.file:
        path: '{{ home_directory }}/Downloads/fonts'
        state: absent
...
