---
- name: Import desktop tasks for ubuntu
  import_tasks: ubuntu.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Download official VNC viewer
  get_url:
    url: https://www.realvnc.com/download/file/viewer.files/VNC-Viewer-6.21.1109-Linux-x64
    dest: '{{ home_bin_directory }}/vnc-viewer'
    mode: '0750'
...
