---
- name: Import font tasks
  ansible.builtin.import_tasks: fonts.yml
  tags:
    - fonts

- name: Import desktop tasks for Ubuntu
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Import desktop tasks for Arch
  ansible.builtin.import_tasks: arch.yml
  when: ansible_facts['os_family']|lower == 'archlinux'
...
