---
- name: Install desktop packages
  apt:
    package:
      - gnome-boxes
      - gnome-tweaks
      - lm-sensors
      - pavucontrol
      - steam
      - tilix
      - ucf
      - vdpauinfo
      - vim-gtk3
      - virt-viewer
      - xsel

- name: Install google-chrome-stable
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: Remove gnome-keyring ssh agent
  file:
    src: /dev/null
    dest: /etc/xdg/autostart/gnome-keyring-ssh.desktop
    state: link
    force: yes
  when: ansible_facts['lsb']['id']|lower == 'pop'
...
