---
- name: Install desktop packages
  apt:
    package:
      - kitty
      - gnome-boxes
      - gnome-tweaks
      - lm-sensors
      - pavucontrol
      - steam
      - tilix
      - ucf
      - vdpauinfo
      - vim-gtk3
      - virt-viewer
      - xsel

- name: Install google-chrome-stable
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: Download official VNC viewer
  get_url:
    url: https://www.realvnc.com/download/file/viewer.files/VNC-Viewer-6.21.1109-Linux-x64
    dest: '{{ home_bin_directory }}/vnc-viewer'
    mode: '0750'

- name: Remove gnome-keyring ssh agent
  file:
    src: /dev/null
    dest: /etc/xdg/autostart/gnome-keyring-ssh.desktop
    state: link
    force: yes
  when: ansible_facts['lsb']['id']|lower == 'pop'
...
