---
- name: Import samba tasks for ubuntu
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Ensure samba is enabled
  ansible.builtin.systemd:
    name: smbd
    state: started
    enabled: true

- name: Update samba config file
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: "644"
  notify:
    - reload samba
...
