---
- name: Import samba client tasks for ubuntu
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Import samba client tasks for arch
  ansible.builtin.import_tasks: arch.yml
  when: ansible_facts['os_family']|lower == 'archlinux'

- name: Create mount directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '750'
    owner: kincerb
    group: kincerb
  loop:
    - /net/google
    - /net/isos
    - /net/plex
    - /etc/secrets

- name: Copy samba credentials file
  ansible.builtin.copy:
    src: credentials
    dest: /etc/secrets/samba.credentials
    owner: kincerb
    group: kincerb
    mode: '600'

- name: Add mounts from file-server
  ansible.builtin.blockinfile:
    path: /etc/fstab
    backup: true
    state: present
    block: |
      //file-server.lan/isos /net/isos cifs credentials=/etc/secrets/samba.credentials,user,uid=1000,gid=1000,iocharset=utf8,noauto,exec,x-gvfs-show 0 0
      //file-server.lan/google /net/google cifs credentials=/etc/secrets/samba.credentials,user,uid=1000,gid=1000,iocharset=utf8,noauto,exec,x-gvfs-show 0 0
      //plex.lan/plex /net/plex cifs credentials=/etc/secrets/samba.credentials,user,uid=1000,gid=1000,iocharset=utf8,noauto,exec,x-gvfs-show 0 0
  notify:
    - Reload Systemd
...
