---
- name: Import development tasks for ubuntu
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Import development tasks for RHEL
  ansible.builtin.import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Create venv for neovim # noqa package-latest
  ansible.builtin.pip:
    name: "{{ item }}"
    virtualenv: "{{ venvs_directory }}/neovim"
    virtualenv_command: python3 -m venv
    state: latest
  loop:
    - pynvim
    - pip
