---
- name: Install development tasks for ubuntu
  import_tasks: ubuntu.yml
  when: ansible_facts['distribution']|lower == 'ubuntu'

- name: Install development tasks for RHEL
  import_tasks: redhat.yml
  when: ansible_facts['distribution']|lower == 'redhat'
...
