---
- name: Enable the optional rpms repository on RHEL6
  rhsm_repository:
    name: rhel-6-server-optional-rpms
    state: enabled
  when: ansible_facts['distribution_major_version'] == '6'

- name: Install development packages
  yum:
    name:
      - "@Development tools"
      - expat-devel
      - keyutils-libs-devel
      - krb5-devel
      - zlib-devel
      - ncurses-devel
      - gdbm-devel
      - xz-devel
      - readline-devel
      - libcom_err-devel
      - libuuid-devel
      - libcurl-devel
      - kernel-headers
      - openssl
      - openssl-devel
      - sqlite-devel
      - bzip2-devel

- name: Install RHEL6 development packages
  yum:
    name:
      - libidn-devel
      - db4-devel
      - valgrind-devel
  when: ansible_facts['distribution_major_version'] == '6'

- name: Install RHEL7+ development packages
  yum:
    name:
      - libdb-devel
      - libffi-devel
  when: ansible_facts['distribution_major_version'] != '6'
...
