---
- name: Install devlopment packages
  yum:
    name: '{{ package }}'
  vars:
    package:
      - "Development tools"
      - zlib-devel
      - ncurses-devel
      - gdbm-devel
      - xz-devel
      - readline-devel
      - libuuid-devel
      - openssl-devel
      - sqlite-devel
      - bzip2-devel
      - libffi-devel
...
