---
- name: Install development packages
  become: true
  ansible.builtin.apt:
    package:
      - build-essential
      - checkinstall
      - libreadline-dev
      - libncurses-dev
      - libssl-dev
      - libsqlite3-dev
      - tk-dev
      - libgdbm-dev
      - libbz2-dev
...
