---
- name: Install common packages
  become: true
  community.general.pacman:
    name:
      - bat
      - neovim
      - nodejs
      - rsync
      - socat
      - starship
      - the_silver_searcher
      - tmux
      - vim
      - xsel
    state: present
    update_cache: yes
...
