---
- name: Install common packages
  become: true
  community.general.pacman:
    name:
      - atuin
      - bat
      - ctags
      - eza
      - fd
      - fish
      - libstdc++5
      - go
      - lazygit
      - neovim
      - nodejs
      - npm
      - python-pip
      - ripgrep
      - rsync
      - socat
      - starship
      - tmux
      - xsel
      - wl-clipboard
      - yamllint
    state: present
    update_cache: true
  register: packages_installed

- name: Create link to bat from batcat
  become: true
  ansible.builtin.file:
    src: /usr/bin/bat
    dest: /usr/bin/batcat
    state: link
  when: "'bat' in packages_installed.packages"
# vim: ft=yaml.ansible
