---
- name: Install common packages
  become: true
  community.general.pacman:
    name:
      - bat
      - neovim
      - nodejs
      - npm
      - python-pip
      - rsync
      - socat
      - starship
      - the_silver_searcher
      - tmux
      - vim
      - xsel
    state: present
    update_cache: yes
  register: packages_installed

- name: Create link to bat from batcat
  become: true
  file:
    src: /usr/bin/bat
    dest: /usr/bin/batcat
    state: link
  when: "'bat' in packages_installed.packages"
...
