---
- name: Install common packages
  pacman:
    name:
      - bat
      - nodejs
      - ranger
      - rsync
      - socat
      - the_silver_searcher
      - tmux
      - vim
      - xsel
    state: present
    update_cache: yes
...
