---
- name: Get nerd fonts and install
  block:
    - name: Create fonts download directory
      become: false
      ansible.builtin.file:
        path: '{{ home_directory }}/Downloads/fonts'
        state: directory

    - name: Create install directory for fonts
      become: true
      ansible.builtin.file:
        path: '{{ font_info.install_directory }}/{{ item }}'
        state: directory
        mode: 0755
      loop: '{{ font_info.names }}'

    - name: Download fonts
      become: false
      ansible.builtin.get_url:
        url: '{{ font_info.url }}/{{ item }}.zip'
        dest: '{{ home_directory }}/Downloads/fonts'
      loop: '{{ font_info.names }}'

    - name: Install fonts
      become: true
      ansible.builtin.unarchive:
        src: '{{ home_directory }}/Downloads/fonts/{{ item }}.zip'
        dest: '{{ font_info.install_directory }}/{{ item }}'
        remote_src: true
        mode: 0755
      loop: '{{ font_info.names }}'

    - name: Update font cache
      become: true
      ansible.builtin.command:
        cmd: fc-cache

  always:
    - name: Remove downloaded fonts
      ansible.builtin.file:
        path: '{{ home_directory }}/Downloads/fonts'
        state: absent
...
