---
- name: Setup authentication
  ansible.builtin.import_tasks: auth.yml
  tags:
    - auth
    - ssh
    - never

- name: Setup configuration files
  ansible.builtin.import_tasks: config.yml
  tags:
    - config
    - never
...
# vim: set ft=yaml.ansible ts=2 sts=2 sw=2:
