---
- name: Setup authentication
  ansible.builtin.import_tasks: auth.yml
  tags:
    - auth
    - never

- name: Setup configuration files
  ansible.builtin.import_tasks: config.yml
  tags:
    - config

- name: Install appimages
  ansible.builtin.include_tasks:
    file: install_appimage.yml
    apply:
      vars:
        appimage: "{{ item }}"
      tags:
        - appimage
  loop: "{{ common_appimages }}"
  tags:
    - appimage
    - never

- name: Run common tasks for Ubuntu
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_facts['os_family']|lower == 'debian'
...
# vim: set ft=yaml.ansible ts=2 sts=2 sw=2:
