---
- name: Get ~/.bashrc stats
  become: no
  stat:
    path: "{{ home_directory }}/.bashrc"
  register: bashrc_stat

- name: Create my default directories
  become: no
  import_tasks: dirs.yml

- name: Add personal SSH keys
  authorized_key:
    user: kincerb
    state: present
    key: '{{ item }}'
  with_file:
    - "{{ ssh_directory }}/kincerb_gpg_auth1.pub"
    - "{{ ssh_directory }}/kincerb_gpg_auth2.pub"
    - "{{ ssh_directory }}/kincerb_forwarder.pub"

- name: Create sudoers.d file for kincerb
  copy:
    src: 01-kincerb
    dest: /etc/sudoers.d/01-kincerb
    owner: root
    group: root
    mode: 0600

- name: Create profile.d file for my shell defaults
  copy:
    src: 01-nucoder.sh
    dest: /etc/profile.d/01-nucoder.sh
    owner: root
    group: root
    mode: 0644

- name: Disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^PermitRootLogin\s+(no|yes)'
    line: 'PermitRootLogin no'
  notify:
    - reload sshd

- name: Enable agent forwarding
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^[#]?AllowAgentForwarding\s+(no|yes)'
    line: 'AllowAgentForwarding yes'
  notify:
    - reload sshd

- name: Enable TCP forwading
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^[#]?AllowTcpForwarding\s+(no|yes)'
    line: 'AllowTcpForwarding yes'
  notify:
    - reload sshd

- name: Enable X11 forwading
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^[#]?X11Forwarding\s+(no|yes)'
    line: 'X11Forwarding yes'
  notify:
    - reload sshd

- name: Install needed packages on Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_facts['distribution']|lower == 'ubuntu'

- name: Clone config-files to setup shell
  become: no
  git:
    repo: 'https://github.com/kincerb/config-files.git'
    dest: "{{ projects_directory }}/config-files"

- name: Set permissions for executables in config-files
  become:  no
  file:
    path: "{{ projects_directory }}/config-files/bin/git-helper.py"
    mode: '0750'

- name: Remove ~/.bashrc provided by vendor
  become:  no
  file:
    path: "{{ home_directory }}/.bashrc"
    state: absent
  when: bashrc_stat.stat.islnk is defined and bashrc_stat.stat.islnk == False

- name: Create symlinks for environment
  become: no
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "{{ projects_directory }}/config-files/alacritty", dest: "{{ config_directory }}/alacritty" }
    - { src: "{{ projects_directory }}/config-files/ansible", dest: "{{ config_directory }}/ansible" }
    - { src: "{{ projects_directory }}/config-files/bash.d", dest: "{{ config_directory }}/bash.d" }
    - { src: "{{ projects_directory }}/config-files/tmux", dest: "{{ config_directory }}/tmux" }
    - { src: "{{ projects_directory }}/config-files/.vimrc", dest: "{{ home_directory }}/.vimrc" }
    - { src: "{{ projects_directory }}/config-files/.bashrc", dest: "{{ home_directory }}/.bashrc" }
    - { src: "{{ projects_directory }}/config-files/.tmux.conf", dest: "{{ home_directory }}/.tmux.conf" }
    - { src: "{{ projects_directory }}/config-files/.ideavimrc", dest: "{{ home_directory }}/.ideavimrc" }
    - { src: "{{ projects_directory }}/config-files/.gitconfig", dest: "{{ home_directory }}/.gitconfig" }
    - { src: "{{ projects_directory }}/config-files/bin/git-helper.py", dest: "{{ home_bin_directory }}/git-helper.py" }
    - { src: /usr/bin/batcat, dest: "{{ home_bin_directory }}/bat" }
    - { src: "{{ config_directory }}/ansible/ansible.cfg", dest: "{{ home_directory }}/.ansible.cfg" }
    - { src: "{{ projects_directory }}/config-files/vim/coc-settings.json", dest: "{{ home_directory }}/.vim/coc-settings.json" }

- name: Install user python packages
  import_tasks: python.yml
...
