---
- name: Get nodejs setup script and install
  block:
    - name: Download script
      get_url: 
        url: https://deb.nodesource.com/setup_15.x
        dest: /tmp/node_setup_15.x.sh
        mode: '0750'

    - name: Run nodejs setup script
      shell:
        cmd: /tmp/node_setup_15.x.sh
        creates: /usr/bin/node

    - name: Install nodejs via apt
      apt:
        name: nodejs

  always:
    - name: Remove nodejs setup script
      file:
        path: /tmp/node_setup_15.x.sh
        state: absent
      ignore_errors: true
...
