---
- name: Get nodejs setup script and install
  block:
    - name: Download script
      get_url: 
        url: https://deb.nodesource.com/setup_17.x
        dest: /tmp/node_setup_17.x.sh
        mode: '0750'

    - name: Run nodejs setup script
      become: true
      command: /tmp/node_setup_17.x.sh
      args:
        creates: /usr/bin/node

    - name: Install nodejs via apt
      become: true
      apt:
        name: nodejs

  always:
    - name: Remove nodejs setup script
      file:
        path: /tmp/node_setup_17.x.sh
        state: absent
      ignore_errors: true # noqa ignore-errors
...
