---
- name: Install common packages for RHELx
  yum:
    name:
      - curl
      - gcc
      - git
      - gnupg2
      - gzip
      - rsync
      - unzip
      - vim-enhanced
      - wget
      - xz

- name: Install common packages for RHEL6
  yum:
    name: libselinux-python
  when: ansible_facts['distribution_major_version'] == '6'

- name: Install common packages for RHEL7
  yum:
    name:
      - python3
      - python3-devel
      - python3-pip
  when: ansible_facts['distribution_major_version'] == '7'

- name: Install common packages for RHEL8
  yum:
    name:
      - python38
      - python38-devel
      - python38-pip
  when: ansible_facts['distribution_major_version'] == '8'
...
