---
all:
  hosts:
    oryxpro:
    gpd3:
    r820:
    penguin:
    titan:
    nuc:
    pi4b:
    p14:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    tools:
      hosts:
        p620:
          services:
            - atuin
            - plex
    p620vms:
      hosts:
        rhel9.3:
          ansible_ssh_common_args: "-o ProxyJump=p620"
        inttools01:
        win11pro:
        workvm:
      vars:
        ansible_ssh_common_args: "-o ProxyJump=p620"
    ssh_proxy:
      hosts:
        inttools01:
        workvm:
    squid:
      hosts:
        inttools01:
          ext_interface: enp1s0
    digitalocean:
      hosts:
        exttools01:
    desktop:
      hosts:
        oryxpro:
        penguin:
        titan:
        nuc:
        gpd3:
        p620:
        workvm:
        p14:
    development:
      hosts:
        oryxpro:
        gpd3:
        inttools01:
    docker:
      hosts:
        exttools01:
        exttools02:
        oryxpro:
        titan:
        workvm:
        p14:
        inttools01:
    kvm:
      hosts:
        oryxpro:
        titan:
        p14:
        p620:
    zfs:
      hosts:
        p620:
    samba:
      hosts:
        p620:
          smb_shares:
            - name: google
              dir: /data/google
              users:
                - kincerb
            - name: isos
              dir: /data/isos
              users:
                - kincerb
            - name: media
              dir: /data/media
              users:
                - kincerb
    samba_client:
      hosts:
        nuc:
        p14:
        oryxpro:
        exttools01:
        garuda-mate:
        gpd3:
        titan:
        workvm:
