---
all:
  hosts:
    oryxpro:
    gpd3:
    r820:
    penguin:
    titan:
    nuc:
    exttools01:
    pi4b:
    p14:
    p620:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    tools:
      p620:
        services:
          - atuin
          - plex
    vms:
      children:
        titanvms:
          hosts:
            workvm:
          vars:
            ansible_ssh_common_args: "-o ProxyJump=titan.lan"
        r820vms:
          hosts:
            wireguard01:
            garuda-mate:
            rhel7-python-build:
            rhel9.3:
            inttools01:
            win11pro:
            file-server:
              virtio_shares:
                - name: google_dataset
                  mountpoint: /google
                - name: isos_dataset
                  mountpoint: /isos
            plex:
              virtio_shares:
                - name: plex_dataset
                  mountpoint: /plex
          vars:
            ansible_ssh_common_args: "-o ProxyJump=r820.lan"
    ssh_proxy:
      hosts:
        garuda-mate:
        wireguard01:
        workvm:
    squid:
      hosts:
        wireguard01:
          ext_interface: enp1s0
    wireguard:
      hosts:
        wireguard01:
        exttools01:
          ext_interface: eth0
    digitalocean:
      hosts:
        exttools01:
    desktop:
      hosts:
        oryxpro:
        penguin:
        titan:
        nuc:
        gpd3:
        garuda-mate:
        workvm:
        p14:
    development:
      hosts:
        oryxpro:
        gpd3:
        garuda-mate:
        rhel7-python-build:
          ansible_python_interpreter:
    docker:
      hosts:
        r820:
          docker_data_dir: /tank-bay1/docker
        exttools01:
        oryxpro:
        titan:
        workvm:
        wireguard01:
        inttools01:
        p620:
    kvm:
      hosts:
        r820:
        oryxpro:
        titan:
        p620:
    zfs:
      hosts:
        p620:
    samba:
      hosts:
        file-server:
          smb_shares:
            - name: google
              dir: /google
              users:
                - kincerb
            - name: isos
              dir: /isos
              users:
                - kincerb
        plex:
          smb_shares:
            - name: plex
              dir: /plex
              users:
                - kincerb
    samba_client:
      hosts:
        nuc:
        p14:
        oryxpro:
        exttools01:
        garuda-mate:
        gpd3:
        titan:
        workvm:
