---
all:
  hosts:
    r820:
      docker_data_dir: /tank-bay1/docker
    file-server:
      smb_shares:
        -
          name: google
          dir: /google
          users:
            - kincerb
        -
          name: isos
          dir: /isos
          users:
            - kincerb
    access:
    nuc:
    oryxpro:
    rhel6-python-build:
      ansible_python_interpreter:
    titan:
  children:
    digitalocean:
      hosts:
        access:
    home:
      hosts:
        nuc:
        r820:
        file-server:
        oryxpro:
        rhel6-python-build:
        titan:
    desktop:
      hosts:
        nuc:
        r820:
        file-server:
        oryxpro:
        titan:
    docker:
      hosts:
        r820:
        oryxpro:
        titan:
    kvm:
      hosts:
        r820:
        oryxpro:
        titan:
    samba:
      hosts:
        file-server:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    home_directory: "{{ lookup('env', 'HOME') }}"
    home_bin_directory: '{{ home_directory }}/.local/bin'
    projects_directory: '{{ home_directory }}/Projects'
    config_directory: '{{ home_directory }}/.config'
    ssh_directory: '{{ home_directory }}/.ssh'
    ssh_socket_directory: '{{ ssh_directory }}/socket'
...
