---
all:
  hosts:
    r820:
      docker_data_dir: /tank-bay1/docker
    access:
    nuc:
  children:
    digitalocean:
      hosts:
        access:
    home:
      hosts:
        nuc:
        r820:
    docker:
      hosts:
        r820:
    kvm:
      hosts:
        r820:
  vars:
    ansible_python_interpreter: /usr/bin/python3
...
