---
squid:
  hosts:
    wireguard01:
      ext_interface: enp1s0
wireguard:
  hosts:
    wireguard01:
    exttools01:
      ext_interface: eth0
digitalocean:
  hosts:
    access:
    exttools01:
workvm:
  hosts:
    garudavm:
home:
  hosts:
    wireguard01:
    nuc:
    r820:
    file-server:
    oryxpro:
    rhel6-python-build:
    rhel7-python-build:
    rhel8-python-build:
    penguin:
    plex:
    titan:
desktop:
  hosts:
    oryxpro:
    titan:
    nuc:
development:
  hosts:
    rhel6-python-build:
      ansible_python_interpreter:
    rhel7-python-build:
      ansible_python_interpreter:
    rhel8-python-build:
      ansible_python_interpreter:
docker:
  hosts:
    r820:
      docker_data_dir: /tank-bay1/docker
    exttools01:
    oryxpro:
    titan:
kvm:
  hosts:
    r820:
    oryxpro:
    titan:
samba:
  hosts:
    file-server:
      smb_shares:
        -
          name: google
          dir: /google
          users:
            - kincerb
        -
          name: isos
          dir: /isos
          users:
            - kincerb
    plex:
      smb_shares:
        -
          name: plex
          dir: /plex
          users:
            - kincerb
samba_client:
  hosts:
    oryxpro:
    exttools01:
kvm_guests:
  hosts:
    file-server:
      virtio_shares:
        - google_dataset
        - isos_dataset
    plex:
      virtio_shares:
        - plex_dataset
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
...
