---
all:
  hosts:
    oryxpro:
    gpd3:
    r820:
    penguin:
    titan:
    nuc:
    file-server:
    wireguard01:
    plex:
    garuda-mate-vm:
    rhel7-python-build:
    rhel9.3:
    inttools01:
    exttools01:
    pi4b:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    physical:
      hosts:
        oryxpro:
        gpd3:
        r820:
        penguin:
        titan:
        nuc:
    ssh_proxy:
      hosts:
        garuda-mate-vm:
        wireguard01:
    squid:
      hosts:
        wireguard01:
          ext_interface: enp1s0
    wireguard:
      hosts:
        wireguard01:
        exttools01:
          ext_interface: eth0
    digitalocean:
      hosts:
        exttools01:
    desktop:
      hosts:
        oryxpro:
        penguin:
        titan:
        nuc:
        gpd3:
        garuda-mate-vm:
    development:
      hosts:
        oryxpro:
        gpd3:
        garuda-mate-vm:
        rhel6-python-build:
          ansible_python_interpreter:
        rhel7-python-build:
          ansible_python_interpreter:
        rhel8-python-build:
          ansible_python_interpreter:
    docker:
      hosts:
        r820:
          docker_data_dir: /tank-bay1/docker
        exttools01:
        oryxpro:
        titan:
        wireguard01:
        inttools01:
    kvm:
      hosts:
        r820:
        oryxpro:
        titan:
    samba:
      hosts:
        file-server:
          smb_shares:
            - name: google
              dir: /google
              users:
                - kincerb
            - name: isos
              dir: /isos
              users:
                - kincerb
        plex:
          smb_shares:
            - name: plex
              dir: /plex
              users:
                - kincerb
    samba_client:
      hosts:
        nuc:
        oryxpro:
        exttools01:
        garudavm:
        garuda-mate-vm:
        gpd3:
        titan:
    kvm_guest:
      hosts:
        file-server:
          virtio_shares:
            - name: google_dataset
              mountpoint: /google
            - name: isos_dataset
              mountpoint: /isos
        plex:
          virtio_shares:
            - name: plex_dataset
              mountpoint: /plex
---
# vim: ft=yaml
