---
- name: Setup and install docker on ubuntu
  import_tasks: ubuntu.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Setup and install docker on Arch
  import_tasks: arch.yml
  when: ansible_facts['os_family']|lower == 'archlinux'

- name: Add kincerb to docker group
  ansible.builtin.user:
    name: kincerb
    append: yes
    groups:
      - docker

- name: Add daemon.json file
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0600
  notify:
    - restart docker
