---
- name: Setup and install docker on ubuntu
  import_tasks: ubuntu.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Ensure docker is enabled
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add kincerb to docker group
  user:
    name: kincerb
    append: yes
    groups:
      - docker

- name: Add daemon.json file
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0600
  when: docker_data_dir is defined
  notify:
    - restart docker
...
