---
- name: Setup and install docker on ubuntu
  import_tasks: ubuntu.yml
  when: ansible_facts['distribution']|lower == 'ubuntu'

- name: Get docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 755

- name: Ensure docker is enabled
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add kincerb to docker group
  user:
    name: kincerb
    append: yes
    groups:
      - docker
...
