---
common_home_directory: "{{ lookup('env', 'HOME') }}"
common_directories:
    appimage: "{{ common_home_directory }}/Applications"
    local_bin: "{{ common_home_directory }}/.local/bin"
    projects: "{{ common_home_directory }}/Projects"
    config: "{{ common_home_directory }}/.config"
    ssh: "{{ common_home_directory }}/.ssh"
    ssh_socket: "{{ common_home_directory }}/.ssh/socket"
common_appimages:
    - name: WezTerm
      user: wez
      repo: wezterm
      url_prefix: https://github.com
      asset_prefix: WezTerm-
      asset_suffix: -Ubuntu20.04.AppImage
      asset_include_tag: true
      dest_name: WezTerm.AppImage
      link_name: wezterm
    - name: Neovim
      user: neovim
      repo: neovim
      url_prefix: https://github.com
      asset_prefix: nvim
      asset_suffix: .appimage
      asset_include_tag: false
      dest_name: nvim.AppImage
      link_name: nvim
common_git_software:
    - name: Delta
      user: dandavison
      repo: delta
      url_prefix: https://github.com
      asset_prefix: delta-
      asset_suffix: -x86_64-unknown-linux-gnu.tar.gz
      asset_include_tag: true
      bin_name: delta
      link_name:
...
# vim: ft=yaml.ansible
