---
common_home_directory: "{{ lookup('env', 'HOME') }}"
common_directories:
    appimage: "{{ common_home_directory }}/Applications"
    local_bin: "{{ common_home_directory }}/.local/bin"
    projects: "{{ common_home_directory }}/Projects"
    config: "{{ common_home_directory }}/.config"
    ssh: "{{ common_home_directory }}/.ssh"
    ssh_socket: "{{ common_home_directory }}/.ssh/socket"
common_appimages:
    - name: WezTerm
      user: wez
      repo: wezterm
      url_prefix: https://github.com
      asset_prefix: WezTerm-
      asset_suffix: -Ubuntu20.04.AppImage
      asset_include_tag: true
      dest_name: WezTerm.AppImage
      link_name: wezterm
common_user_id: kincerb
...
# vim: ft=yaml.ansible
