---
home_directory: "{{ ansible_facts['env']['HOME'] }}"
home_bin_directory: '{{ home_directory }}/.local/bin'
projects_directory: '{{ home_directory }}/Projects'
config_directory: '{{ home_directory }}/.config'
ssh_directory: '{{ home_directory }}/.ssh'
ssh_socket_directory: '{{ ssh_directory }}/socket'
font_info:
  url: https://github.com/ryanoasis/nerd-fonts/releases/download/2.2.0-RC
  install_directory: /usr/local/share/fonts
  names:
    - AnonymousPro
    - CascadiaCode
    - FiraCode
    - Hack
    - IBMPlexMono
    - Inconsolata
    - JetBrainsMono
    - Mononoki
    - SourceCodePro
    - Terminus
    - Ubuntu
...
