---
home_directory: "{{ lookup('env', 'HOME') }}"
home_bin_directory: "{{ home_directory }}/.local/bin"
projects_directory: "{{ home_directory }}/Projects"
config_directory: "{{ home_directory }}/.config"
ssh_directory: "{{ home_directory }}/.ssh"
ssh_socket_directory: "{{ ssh_directory }}/socket"
compose_version: '1.28.2'
...
