---
- name: Import wireguard tasks for ubuntu
  import_tasks: ubuntu.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Add IP forwarding support
  copy:
    src: 99-wireguard.conf
    dest: /etc/sysctl.d/99-wireguard.conf
    owner: root
    group: root
    mode: 0644
  register:
    ipforwarding

- name: Activate IP forwarding
  command: sysctl -p /etc/sysctl.d/99-wireguard.conf
  when: ipforwarding is changed

- name: Create key pair
  shell:
    chdir: /etc/wireguard
    cmd: wg genkey |tee privatekey |wg publickey > publickey
    creates: /etc/wireguard/*key

- name: Set proper permissions on keys
  file:
    path: '{{ item }}'
    owner: root
    group: root
    mode: '0700'
  loop:
    - /etc/wireguard/privatekey
    - /etc/wireguard/publickey
...
